### ISSUE TITLE
Tinkerbell Patches Tracking

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere-build-tooling#811]
This issue is just to track all the patches we have for Tinkerbell and determine if they are needed or not:
### Boots
- [x] Add env for registry cert and tink-worker image #489 

### CAPT
- [x] Remove requirement for machine.Spec.Version #424
- [ ] Mutex lock for hardware selection #543 

### Hook
  - [ ] Certificate hosting and tink-worker image #489 
  - [ ] Retry for pulling tink-worker image #656 
  
### Tink
- [ ] Make registry cert and tink-worker image url configurable #489
